services:

  nginx:
    build: docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./var/log/nginx:/var/log/nginx
      - ./:/var/www/project
    depends_on:
      - fpm

  fpm:
    build: docker/fpm
    volumes:
      - ./:/var/www/project
